controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

DWAPlannerROS:
   max_vel_x: 4
   min_vel_x: -4
   max_vel_y: 4  # zero for a differential drive robot
   min_vel_y: -4
   max_vel_theta: 8
   min_vel_theta: -8
   min_in_place_vel_theta: 8
   escape_vel: -4
   acc_lim_x: 12
   acc_lim_y: 12  # zero for a differential drive robot
   acc_lim_theta: 10

   holonomic_robot: true
   yaw_goal_tolerance: 6.283 # Don't consider yaw goal
   xy_goal_tolerance: 0.05  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 8
   vy_samples: 8
   vtheta_samples: 20
   dwa: true
   simple_attractor: false






# controller_frequency: 30.0
# recovery_behavior_enabled: false
# clearing_rotation_allowed: false

# DWAPlannerROS:
#    max_vel_x: 1
#    min_vel_x: -1
#    max_vel_y: 0.0  # zero for a differential drive robot
#    min_vel_y: 0.0
#    max_vel_theta: 2
#    min_vel_theta: -2
#    min_in_place_vel_theta: 0.8
#    escape_vel: -1
#    acc_lim_x: 3
#    acc_lim_y: 0.0  # zero for a differential drive robot
#    acc_lim_theta: 2.4

#    holonomic_robot: false
#    yaw_goal_tolerance: 0.1 # about 6 degrees
#    xy_goal_tolerance: 0.05  # 5 cm
#    latch_xy_goal_tolerance: false
#    pdist_scale: 0.4
#    gdist_scale: 0.8
#    meter_scoring: true

#    heading_lookahead: 0.325
#    heading_scoring: false
#    heading_scoring_timestep: 0.8
#    occdist_scale: 0.05
#    oscillation_reset_dist: 0.05
#    publish_cost_grid_pc: false
#    prune_plan: true

#    sim_time: 1.0
#    sim_granularity: 0.05
#    angular_sim_granularity: 0.1
#    vx_samples: 8
#    vy_samples: 0  # zero for a differential drive robot
#    vtheta_samples: 20
#    dwa: true
#    simple_attractor: false